version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.34
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
      MYSQL_ROOT_PASSWORD: teste
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306

